### ISSUE TITLE
coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by NoDataFound** [sim0nx/eml_parser#2]
Have you seen this error before?

```
$ python eml_parser.py 
Traceback (most recent call last):
  File "eml_parser.py", line 515, in <module>
    main()
  File "eml_parser.py", line 507, in main
    m = decode_email(msgfile)
  File "eml_parser.py", line 318, in decode_email
    fp = open(eml_file)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by sim0nx** [comment]
This is not explicit, but if you want to run the module (for testing...) you must specify a "-i <emlfile>" command line parameter with an EML file as input

The main function of the module is a bit stupid as this is not meant for really using, you should include it in your code instead.
